#pragma once
#include <windows.h>
#include <windowsx.h>
#include <stdio.h>
#include <string>
#include <fstream>
#include <tchar.h>
#include <stdlib.h>
#include <conio.h>
#include <iostream>
#include <fstream>
#include <iomanip>
